version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: agentic_db_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: agentic_db
    ports:
      - "5432:5432"
    volumes:
      - "/home/rahul/GlobalStorage_Programming/MiniProject/Pg_data"

